cd /opt/all/netopeer2/bin
export PATH=$PWD:$PATH
cd /opt/all/sysrepo/bin
export PATH=$PWD:$PATH
cd /opt/all/libyang/bin
export PATH=$PWD:$PATH
export YANG_MODULE_DIR=/opt/all/netopeer2/share/yang/modules/netopeer2
export MODULES_PERMS=660
export NP2_MODULE_OWNER=root 
export NP2_MODULE_GROUP=netconf
